import "./globals.css";
import Header from "@/components/header";
import { Roboto } from "next/font/google"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({weight:['400','500','700'],subsets: ['latin']})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
